### ISSUE TITLE
Hosts blocked

### ISSUE THREAD

**Issue by GjBrutello** [WeebDataHoarder/p2pool-nsis#4]
During sync monerod on windows, almost at the end(98%), I got the log:
![monerod_ips_blocked](https://user-images.githubusercontent.com/50217444/144030626-e205bf3e-0b3f-4d6b-b83f-550bee18a10d.png)
Is this okay? I just don't know it's my ISP has blocked the monerod IPs or the monerod servers blocked my IP. Firewall is off.

**Comment by WeebDataHoarder** [comment]
This is normal, monerod behavior. It's just blocking on its own misbehaving peers.
